#!/bin/awk -f

/^\t/ {
	# Fix broken patches: some patches are broken.
	# They have a line that don't start with a space beginning of a line.
	# ex. 9-machsmap, pc-conf-wifi-virtio
	$0 = " " $0
}
/^[^-+ @]/ || $1 == "---" || $1 == "+++" {
	h[++n] = $0
	if($0 ~ /^diff /)
		diff = $0
	else if($1 == "---")
		old = $2
	else if($1 == "+++")
		new = $2
	next
}
{	if(n > 0){
		if(diff == "")
			printf "diff -Nru %s %s\n", old, new
		for(i = 1; i <= n; i++)
			print h[i]
		diff = ""
		n = 0
	}
	print
}
